// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL || '',
  },
  schema: 'src/external/db/prisma/schema.prisma',
  migrations: {
    path: 'src/external/db/prisma/migrations',
  },
})
